
#include "hook_syscall.h"
#include <linux/module.h>
#include <linux/init.h>
#include <linux/types.h>
#include <linux/delay.h>
#include <linux/sched.h>
#include <linux/version.h>
#include <linux/kallsyms.h>
#include <linux/semaphore.h>
#include <asm/cacheflush.h>
#include <linux/bitops.h>
#include <linux/sizes.h>
#include <linux/byteorder/generic.h>
#include <linux/preempt.h>
SYSCALL_EXPORT3(read, unsigned int , fd, char *, buf, size_t , count)
SYSCALL_EXPORT3(write, unsigned int , fd, const char *, buf, size_t , count)
SYSCALL_EXPORT4(openat, int , dfd, const char *, filename, int , flags, umode_t , mode)
SYSCALL_EXPORT1(close, unsigned int , fd)
SYSCALL_EXPORT2(fstat, unsigned int , fd, struct __old_kernel_stat *, statbuf)
SYSCALL_EXPORT4(newfstatat, int , dfd, const char *, filename, struct stat *, statbuf, int , flag)
SYSCALL_EXPORT3(lseek, unsigned int , fd, off_t , offset, unsigned int , whence)
SYSCALL_EXPORT3(ioctl, unsigned int , fd, unsigned int , cmd, unsigned long , arg)
SYSCALL_EXPORT4(pread64, unsigned int , fd, char *, buf, size_t , count, loff_t , pos)
SYSCALL_EXPORT4(pwrite64, unsigned int , fd, const char *, buf, size_t , count, loff_t , pos)
SYSCALL_EXPORT3(readv, unsigned long , fd, const struct iovec *, vec, unsigned long , vlen)
SYSCALL_EXPORT3(writev, unsigned long , fd, const struct iovec *, vec, unsigned long , vlen)
SYSCALL_EXPORT4(sendfile, int , out_fd, int , in_fd, off_t *, offset, size_t , count)
SYSCALL_EXPORT3(fcntl, unsigned int , fd, unsigned int , cmd, unsigned long , arg)
SYSCALL_EXPORT2(flock, unsigned int , fd, unsigned int , cmd)
SYSCALL_EXPORT1(fsync, unsigned int , fd)
SYSCALL_EXPORT1(fdatasync, unsigned int , fd)
SYSCALL_EXPORT2(truncate, const char *, path, long , length)
SYSCALL_EXPORT2(ftruncate, unsigned int , fd, unsigned long , length)
SYSCALL_EXPORT3(getdents64, unsigned int , fd, struct linux_dirent64 *, dirent, unsigned int , count)
SYSCALL_EXPORT2(getcwd, char *, buf, unsigned long , size)
SYSCALL_EXPORT1(chdir, const char *, filename)
SYSCALL_EXPORT4(renameat, int , olddfd, const char * , oldname, int , newdfd, const char * , newname)
SYSCALL_EXPORT3(mkdirat, int , dfd, const char * , pathname, umode_t , mode)
SYSCALL_EXPORT5(linkat, int , olddfd, const char *, oldname, int , newdfd, const char *, newname, int , flags)
SYSCALL_EXPORT3(unlinkat, int , dfd, const char * , pathname, int , flag)
SYSCALL_EXPORT3(symlinkat, const char * , oldname, int , newdfd, const char * , newname)
SYSCALL_EXPORT4(readlinkat, int , dfd, const char *, path, char *, buf, int , bufsiz)
SYSCALL_EXPORT2(fchmod, unsigned int , fd, umode_t , mode)
SYSCALL_EXPORT3(fchmodat, int , dfd, const char * , filename, umode_t , mode)
SYSCALL_EXPORT3(fchown, unsigned int , fd, uid_t , user, gid_t , group)
SYSCALL_EXPORT5(fchownat, int , dfd, const char *, filename, uid_t , user, gid_t , group, int , flag)
SYSCALL_EXPORT3(faccessat, int , dfd, const char *, filename, int , mode)
SYSCALL_EXPORT3(dup3, unsigned int , oldfd, unsigned int , newfd, int , flags)
SYSCALL_EXPORT4(utimensat, int , dfd, const char *, filename, struct timespec *, utimes, int , flags)
SYSCALL_EXPORT6(copy_file_range, int , fd_in, loff_t *, off_in, int , fd_out, loff_t *, off_out, size_t , len, unsigned int , flags)
SYSCALL_EXPORT2(statfs, const char * , path, struct statfs *, buf)
SYSCALL_EXPORT2(fstatfs, unsigned int , fd, struct statfs *, buf)
SYSCALL_EXPORT0(sync)
SYSCALL_EXPORT5(mount, char *, dev_name, char *, dir_name, char *, ty, unsigned long , flags, void *, data)
SYSCALL_EXPORT6(umount2, unsigned long, arg1, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5, unsigned long, arg6)
SYSCALL_EXPORT1(brk, unsigned long , brk)
SYSCALL_EXPORT6(mmap, unsigned long, arg1, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5, unsigned long, arg6)
SYSCALL_EXPORT3(mprotect, unsigned long , start, size_t , len, unsigned long , prot)
SYSCALL_EXPORT2(munmap, unsigned long , addr, size_t , len)
SYSCALL_EXPORT3(madvise, unsigned long , start, size_t , len, int , behavior)
SYSCALL_EXPORT4(rt_sigaction, int, arg1, const struct sigaction *, arg2, struct sigaction *, arg3, size_t, size_t)
SYSCALL_EXPORT4(rt_sigprocmask, int , how, sigset_t *, set, sigset_t *, oset, size_t , sigsetsize)
SYSCALL_EXPORT2(sigaltstack, const struct sigaltstack *, uss, struct sigaltstack *, uoss)
SYSCALL_EXPORT5(clone, unsigned long, arg1, unsigned long, arg2, int *, arg3, int *, arg4, unsigned long, arg5)
SYSCALL_EXPORT3(execve, const char *, filename, const char *const *, argv, const char *const *, envp)
SYSCALL_EXPORT1(exit, int , error_code)
SYSCALL_EXPORT1(exit_group, int , error_code)
SYSCALL_EXPORT4(wait4, pid_t , pid, int *, stat_addr, int , options, struct rusage *, ru)
SYSCALL_EXPORT1(set_tid_address, int *, tidptr)
SYSCALL_EXPORT6(futex, u32 *, uaddr, int , op, u32 , val, struct timespec *, utime, u32 *, uaddr2, u32 , val3)
SYSCALL_EXPORT2(tkill, pid_t , pid, int , sig)
SYSCALL_EXPORT3(setitimer, int , which, struct itimerval *, value, struct itimerval *, ovalue)
SYSCALL_EXPORT2(clock_gettime, clockid_t , which_clock, struct __kernel_timespec *, tp)
SYSCALL_EXPORT0(getpid)
SYSCALL_EXPORT0(gettid)
SYSCALL_EXPORT1(uname, struct old_utsname *, arg1)
SYSCALL_EXPORT1(umask, int , mask)
SYSCALL_EXPORT0(getuid)
SYSCALL_EXPORT0(getgid)
SYSCALL_EXPORT1(setuid, uid_t , uid)
SYSCALL_EXPORT0(geteuid)
SYSCALL_EXPORT0(getegid)
SYSCALL_EXPORT2(setpgid, pid_t , pid, pid_t , pgid)
SYSCALL_EXPORT0(getppid)
SYSCALL_EXPORT0(setsid)
SYSCALL_EXPORT1(getpgid, pid_t , pid)
SYSCALL_EXPORT2(getgroups, int , gidsetsize, gid_t *, grouplist)
SYSCALL_EXPORT2(setgroups, int , gidsetsize, gid_t *, grouplist)
SYSCALL_EXPORT5(prctl, int , option, unsigned long , arg2, unsigned long , arg3, unsigned long , arg4, unsigned long , arg5)
SYSCALL_EXPORT2(membarrier, int , cmd, int , flags)
SYSCALL_EXPORT3(rt_sigqueueinfo, pid_t , pid, int , sig, siginfo_t *, uinfo)
SYSCALL_EXPORT3(finit_module, int , fd, const char *, uargs, int , flags)
SYSCALL_EXPORT3(open, const char *, filename, int , flags, umode_t , mode)
SYSCALL_EXPORT2(stat, const char *, filename, struct __old_kernel_stat *, statbuf)
SYSCALL_EXPORT2(lstat, const char *, filename, struct __old_kernel_stat *, statbuf)
SYSCALL_EXPORT2(access, const char *, filename, int , mode)
SYSCALL_EXPORT2(dup2, unsigned int , oldfd, unsigned int , newfd)
SYSCALL_EXPORT0(fork)
SYSCALL_EXPORT0(vfork)
SYSCALL_EXPORT2(rename, const char *, oldname, const char *, newname)
SYSCALL_EXPORT2(mkdir, const char *, pathname, umode_t , mode)
SYSCALL_EXPORT1(rmdir, const char *, pathname)
SYSCALL_EXPORT2(link, const char *, oldname, const char *, newname)
SYSCALL_EXPORT1(unlink, const char *, pathname)
SYSCALL_EXPORT3(readlink, const char *, path, char *, buf, int , bufsiz)
SYSCALL_EXPORT6(arch_prctl, unsigned long, arg1, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5, unsigned long, arg6)
